env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent: ["error", 2]
  linebreak-style: ["error", "unix"]
  quotes: ["error", "double"]
  semi: ["error", "never"]
  arrow-parens: ["error", "as-needed"]
  arrow-spacing: error
  comma-dangle: ["error", "never"]
  space-in-parens: ["error", "never"]
  array-bracket-spacing: ["error", "never"]
  no-trailing-spaces: "error"
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
      caughtErrorsIgnorePattern: ^_
overrides:
  - files: [".eleventy.js", "eleventy/*.js" ]
    env:
      node: true
    rules:
      "@typescript-eslint/no-var-requires": "off"
